const express = require('express');
const competitionController = require('./competition.controller');
const authMiddleware = require('../../middleware/auth');
const roleMiddleware = require('../../middleware/role');
const router = express.Router();
const upload = require('../../middleware/upload');
router.get('/', competitionController.getAllCompetitions);
router.get('/me', authMiddleware.protect, roleMiddleware.restrictTo('RECRUITER'), competitionController.getMyCompetitions);
router.get('/:id', competitionController.getCompetition);
router.use(authMiddleware.protect);
router.post('/:id/register', roleMiddleware.restrictTo('STUDENT'), competitionController.registerCompetition);
router.post('/:id/unregister', roleMiddleware.restrictTo('STUDENT'), competitionController.unregisterCompetition);
router.post('/', roleMiddleware.restrictTo('SUPER_ADMIN', 'RECRUITER'), upload.uploadImage, competitionController.createCompetition);
router.patch('/:id', roleMiddleware.restrictTo('RECRUITER'), upload.uploadImage, competitionController.updateCompetition);
router.delete('/:id', roleMiddleware.restrictTo('RECRUITER'), competitionController.deleteCompetition);
module.exports = router;
