const express = require('express');
const authController = require('./auth.controller');
const authMiddleware = require('../../middleware/auth');
const { loginLimiter } = require('../../middleware/rateLimiter');
const { uploadImage } = require('../../middleware/upload');
const router = express.Router();
router.post('/register', authController.register);
router.post('/login', loginLimiter, authController.login);
router.post('/google', authController.googleAuth);
router.post('/send-otp', authController.sendOTP);
router.post('/verify-otp', authController.verifyOTP);
router.post('/admin/login', loginLimiter, authController.adminLogin);
router.post('/forgot-password', authController.forgotPassword);
router.post('/check-reset-otp', authController.checkResetOTP);
router.post('/reset-password', authController.resetPassword);
router.use(authMiddleware.protectAny); 
router.post('/assign-role', authController.assignRole);
router.post('/upload-avatar', uploadImage, authController.uploadAvatar);
router.get('/me', authController.getMe);
router.post('/update-profile', authController.updateProfile);
module.exports = router;