const express = require('express');
const studentController = require('./student.controller');
const authMiddleware = require('../../middleware/auth');
const roleMiddleware = require('../../middleware/role');
const { uploadImage, uploadResume } = require('../../middleware/upload');
const router = express.Router();
router.use(authMiddleware.protect);
router.get('/me', roleMiddleware.restrictTo('STUDENT'), studentController.getMe);
router.post('/profile', roleMiddleware.restrictTo('STUDENT'), studentController.createOrUpdateProfile);
router.patch('/profile/image', roleMiddleware.restrictTo('STUDENT'), uploadImage, studentController.uploadImage);
router.patch('/profile/resume', roleMiddleware.restrictTo('STUDENT'), uploadResume, studentController.uploadResume);
router.get('/:id', studentController.getStudentProfile);
module.exports = router;